name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: |
          xcodebuild clean -project WDBFontOverwrite.xcodeproj -scheme WDBFontOverwrite -configuration Release
          xcodebuild archive -project WDBFontOverwrite.xcodeproj -scheme WDBFontOverwrite -destination 'platform=iOS Simulator,name=iPhone 11' -configuration Release -archivePath WDBFontOverwrite.xcarchive
          # xcodebuild -exportArchive -archivePath WDBFontOverwrite.xcarchive -exportOptionsPlist .github/script/ExportOptionsSDKDemoDevelop.plist -exportPath ./

      
      - name: Upload NETSDK Library
        uses: actions/upload-artifact@v4
        with:
          name: WDBFontOverwrite.xcarchive
          path: WDBFontOverwrite.xcarchive
